### ISSUE TITLE
panic when pressing enter when all notifications are read

### ISSUE THREAD

**Issue by caarlos0** [tj/triage#18]
## Prerequisites

* [c] I searched to see if the issue already exists.

## Description

when I get to the screen saying "you're all done", if I press enter, I get a panic

## Steps to Reproduce

- read all notifications 
- press enter

```

                                                                                                                             Looks like you're all done 😊panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/tj/triage.Update(0x1693360, 0xc00008d260, 0x1514e40, 0xc0001f3160, 0x153f480, 0xc0004ec000, 0x0, 0xc0004ec000, 0x0)
	/Users/carlos/Code/Go/pkg/mod/github.com/tj/triage@v0.1.0/update.go:295 +0x33f3
github.com/tj/go-tea.(*Program).start(0xc00008d2f0, 0x1693360, 0xc00008d260, 0x6, 0x0)
	/Users/carlos/Code/Go/pkg/mod/github.com/tj/go-tea@v0.2.0/tea.go:200 +0x538
github.com/tj/go-tea.(*Program).Start(0xc00008d2f0, 0x1693360, 0xc00008d260, 0x0, 0x0)
	/Users/carlos/Code/Go/pkg/mod/github.com/tj/go-tea@v0.2.0/tea.go:116 +0x1c1
main.main()
```

## Slack

Join us on Slack https://chat.apex.sh/

I would try to fix it but its almost 4am and I need to 😴,didn't want to forget about it 🙏

**Comment by tj** [comment]
Ah nice hahah.. I'll check this out today, should be a quick fix

**Comment by caarlos0** [comment]
narrator: he did indeed totally forget about it

thanks 🙏
